---
- name: Copy Nginx config file from NAS
  become: true
  copy:
    src: '{{ local_config_backup_dir }}/nginx/'
    dest: /etc/nginx
    owner: root
    group: root
    mode: 0644

- name: Reload Nginx service
  become: true
  service:
    name: nginx
    state: reloaded