
---
- include_tasks: setup.yml
- include_tasks: cockpit-pcp.yml
  when: with_cockpit-pcp
- include_tasks: cockpit-machines.yml
  when: with_cockpit-machines
- include_tasks: cockpit-networkmanager.yml
  when: with_cockpit-networkmanager