
---
- include_tasks: install.yml
- include_tasks: cockpit-pcp.yml
  when: with_cockpit_pcp
- include_tasks: cockpit-machines.yml
  when: with_cockpit_machines
- include_tasks: cockpit-networkmanager.yml
  when: with_cockpit_networkmanager