---
- name: Install Cockpit
  package:
    name:
      - cockpit
    default_release: "{{ ansible_distribution_release }}"
    state: present
    update_cache: yes

- name: Install Cockpit Apps
  package:
    name:
      - cockpit-pcp
      - cockpit-machines
      - qemu-kvm
      - qemu-guest-agent
    state: present
    update_cache: yes

- name: Add libvirt group
  group:
    name: libvirt
    state: present

- name: Add user to group libvirt
  user:
    name: "{{ username }}"
    groups: 
      - libvirt
    state: present
    append: true

- name: Change libvirtd user to username
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    regexp: '^user'
    line: 'user = {{ username }}'
    state: present
    backup: yes
  notify: restart libvirtd

- name: Change libvirtd group to libvirt
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    regexp: '^group'
    line: 'group = libvirt'
    state: present
    backup: yes
  notify: restart libvirtd

- name: Enable IOMMU in GRUB_CMDLINE_LINUX_DEFAULT
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!intel_iommu=on).)*?)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=on"'
    backup: true
    backrefs: true
  notify: update grub
