---
- name: Install Cockpit
  package:
    name:
      - cockpit
    default_release: "{{ ansible_distribution_release }}"
    state: present
    update_cache: yes

- name: Install Cockpit Apps
  package:
    name:
      - cockpit-pcp
      - cockpit-machines
      - qemu-kvm
      - qemu-guest-agent
    state: present
    update_cache: yes