---
- hosts: tester

  roles:
    - role: proxmox
      when: with_proxmox
    - role: system
    - role: netplan
      when: with_netplan
    - role: cockpit
      when: with_cockpit
    - role: docker
      when: with_docker
    - role: wireguard
      when: with_wireguard
    - role: coral
      when: with_coral
    - role: storage
      when: with_storage
    - role: vladgh.samba.server
      when: with_samba
    - role: geerlingguy.nfs
      when: with_nfs
      become: true

  pre_tasks:
    - import_tasks: tasks/platform.yml
    - import_tasks: tasks/rpi.yml