---
- hosts: tester
  become: yes

  vars_files:
    - vars.yml

  roles:
    - role: system
    - role: netplan
      when: with_netplan
    - role: cockpit
      when: with_cockpit
    - role: docker
      when: with_docker
    - role: storage
      when: with_storage
    - role: vladgh.samba.server
      when: with_samba

  pre_tasks:
    - import_tasks: tasks/platform.yml