---
- name: Disable all Enterprise sources
  become: true
  lineinfile:
    dest: '/etc/apt/sources.list.d/{{ item.file }}'
    regexp: '^deb {{ item.url }}*'
    state: absent
    backup: yes
  loop: '{{ pve_enterprise_sources }}'

- name: Check if pve-fake-subscription is installed
  command: dpkg -l pve-fake-subscription
  register: pve_fake_subscription_installed
  ignore_errors: True
  check_mode: False
  changed_when: false

- name: Install pve-fake-subscription
  become: true
  block:
    - get_url:
        url: '{{ pve_fake_subscription_url }}'
        dest: /root/pve-fake-subscription.deb
    - command: dpkg -i pve-fake-subscription.deb
  when: pve_fake_subscription_installed.rc == 1

- name: Prevent fake keys from being checked against the Proxmox servers
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1 shop.maurer-it.com'
    line: "127.0.0.1 shop.maurer-it.com"
    state: present
    backup: yes