---
- name: Clone dotfiles repo
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '/home/{{ username }}/dotfiles'
    force: yes

- name: Change dotfiles folder permissions
  file:
    path: '/home/{{ username }}/dotfiles'
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Remove README file
  file:
    path: '/home/{{ username }}/dotfiles/README.md'
    state: absent

- name: Stow dotfiles
  shell: 
    cmd: 'stow --target $HOME *'
    chdir: '/home/{{ username }}/dotfiles'