---
- name: Clone dotfiles repo
  git:
    repo: '{{ dotfiles_repo }}'
    dest: '/home/{{ username }}/dotfiles'

- name: Change dotfiles folder permissions
  file:
    path: '/home/{{ username }}/dotfiles'
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Stow dotfiles
  shell: 
    cmd: 'stow -v -t /home/{{ username }} */'
    chdir: '/home/{{ username }}/dotfiles'
  register: stow_result
  changed_when: '"LINK" in stow_result.stderr'