---
- name: Set hostname to {{ hostname }}
  become: true
  hostname:
    name: '{{ hostname }}'
  when: lxc_container == 'no'

- name: Set timezone to {{ timezone }}
  become: true
  timezone:
    name: '{{ timezone }}'

- name: Set RAM swappiness
  become: true
  sysctl:
    name: vm.swappiness
    value: '{{ swappiness }}'
    state: present
    reload: true
  when: swappiness is defined

- name: Enable IP forwarding (ipv4)
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
  when: ip_forward == 'yes'