---
- name: Update and upgrade packages 
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists and allow_restart == 'yes'

- name: Install essential packages
  package:
    name: '{{ essential_packages }}'
    state: present
    update_cache: yes

- name: Set hostname to {{ hostname }}
  hostname:
    name: '{{ hostname }}'

- name: Set timezone to {{ timezone }}
  timezone:
    name: '{{ timezone }}'

- name: Set RAM swappiness to 10
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: true
  when: swappiness is defined

- name: Enable IP forwarding (ipv4)
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
  when: ip_forward is defined and ip_forward == 'yes'