---
- name: Copy network config file
  become: true
  copy:
    src: "{{ hostname }}.interfaces"
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Check if networking service exists
  stat: path=/etc/init.d/networking
  register: networking_service_file

- name: Restart system networking
  become: true
  service:
    name: networking
    state: restarted
  when: networking_service_file.stat.exists
  
- name: Check if ifreload is available
  stat:
    path: /usr/sbin/ifreload
  register: ifreload_executable

- name: Run Proxmox ifreload
  become: true
  command: ifreload -a
  when: ifreload_executable.stat.exists