---
- name: 'Add {{ samba_group }} group'
  group:
    name: '{{ samba_group }}'
    gid: 1002
  when: with_samba

- name: 'Ensure all necessary groups exist'
  group:
    name: '{{ item.group }}'
  loop:
    - group: '{{ username }}'
    - group: docker
      when: with_docker
    - group: libvirt
      when: with_cockpit_machines

- name: Setup login user with group sudo and {{ username }}
  user:
    name: "{{ username }}"
    groups: 
      - sudo
      - '{{ username }}'
    append: true

- name: Ensure login user ({{ username }}) is in necessary groups
  user:
    name: "{{ username }}"
    groups: 
      - '{{ item.group }}'
    append: true
  loop:
    - group: '{{ samba_group }}'
      when: with_samba
    - group: docker
      when: with_docker
    - group: libvirt
      when: with_cockpit_machines

- name: Allow {{ username }} user to have passwordless sudo
  template:
    src: passwordless-sudo.j2
    dest: /etc/sudoers.d/passwordless-sudo
    owner: root
    group: root
    mode: 0644