---
- name: Check if containers folder exists
  stat:
    path: '/mnt/Config/{{ ansible_hostname }}/containers'
  register: containers_folder

- name: Upgrade and launch all Docker containers
  community.docker.docker_compose_v2:
    project_src: '/mnt/Config/{{ ansible_hostname }}/containers'
    pull: true
  when: containers_folder.exists

- name: Upgrade and launch Docker containers in {{ containers_dir }}
  community.docker.docker_compose_v2:
    project_src: '{{ containers_dir }}'
    pull: true
  when: containers_folder.exists