---
- name: Install Nginx package
  become: true
  package:
    name:
      - nginx
    state: latest

- name: Ensure Nginx service is running
  become: true
  service:
    name: nginx
    state: restarted
