---
# To reuse previously written tasks as a playbook with Semaphore
- hosts: '{{ target_hosts | default("all") }}'
  become: true
  vars_files:
    - '../../group_vars/all'
  tasks:
    - import_tasks: "tasks/{{ task_name }}.yml"
