---
- name: Ensure nfs-common is installed
  become: true
  package:
    name: nfs-common
    state: present
    update_cache: yes

- name: Mount drives at boot
  become: true
  ansible.posix.mount:
    path: '/mnt/{{ item.name }}'
    src: 'UUID={{ item.uuid }}'
    fstype: '{{ item.ftype }}'
    state: mounted
  loop: '{{ drives }}'
  when: drives is defined

- name: Mount NFS volumes at boot
  become: true
  ansible.posix.mount:
    path: '/mnt/{{ item.name }}'
    src: '{{ item.ip }}:{{ item.dir }}'
    fstype: nfs4
    state: mounted
  loop: '{{ nfs_volumes }}'
  when: nfs_volumes is defined