---
- name: Ensure nfs-common is installed
  package:
    name: nfs-common
    state: present
    update_cache: yes

- name: Mount drives at boot
  ansible.posix.mount:
    path: '/mnt/{{ item.name }}'
    src: 'UUID={{ item.uuid }}'
    fstype: '{{ item.ftype }}'
    state: mounted
  loop: '{{ drives }}'

- name: Mount NFS volumes at boot
  ansible.posix.mount:
    path: '/mnt/{{ item.name }}'
    src: '{{ item.ip }}:{{ item.dir }}'
    fstype: nfs
    state: mounted
  loop: '{{ nfs }}'