---
- name: Check if containers folder exists
  stat:
    path: '/mnt/Config/{{ ansible_hostname }}/containers'
  register: containers_folder

- name: Launch all Docker containers
  community.docker.docker_compose_v2:
    project_src: '/mnt/Config/{{ ansible_hostname }}/containers'
    remove_orphans: true
  when: containers_folder.stat.exists

- name: Launch Docker containers in {{ containers_dir }}
  community.docker.docker_compose_v2:
    project_src: '{{ containers_dir | default("/mnt/storage/containers") }}'
    remove_orphans: true
  when: not containers_folder.stat.exists