---
- name: Check if containers folder exists
  stat:
    path: '/mnt/Config/{{ ansible_hostname }}/containers'
  register: containers_folder

- name: Upgrade and launch all Docker containers
  community.docker.docker_compose_v2:
    project_src: '/mnt/Config/{{ ansible_hostname }}/containers'
    pull: always
    remove_orphans: true
  when: containers_folder.stat.exists

- name: Upgrade and launch Docker containers in {{ containers_dir | default("/mnt/storage/containers") }}
  community.docker.docker_compose_v2:
    project_src: '{{ containers_dir | default("/mnt/storage/containers") }}'
    pull: always
    remove_orphans: true
  when: not containers_folder.stat.exists