---
- name: Fall back to containers folder at /mnt/Config/{{ ansible_hostname }}/containers
  set_facts:
    containers_path: '/mnt/Config/{{ ansible_hostname }}/containers'
  when: containers_path is undefined

- name: Check if containers folder at {{ containers_path }} exists
  stat:
    path: '{{ containers_path }}'
  register: containers_folder

- name: Upgrade and launch all Docker containers
  community.docker.docker_compose_v2:
    project_src: '{{ containers_path }}'
    pull: always
    remove_orphans: true
  when: containers_folder.stat.exists