---
- name: Ensure rsync is installed
  package:
    name:
      - rsync
    state: present

- name: Check if docker-compose file exists to not overwrite containers data
  stat:
    path: '{{ containers_dir }}/{{ compose_file }}'
  register: docker_compose_file

- name: Copy docker-compose file and containers data
  become: false
  synchronize:
    src: '{{ containers_backup_dir}}/'
    dest: '{{ containers_dir }}/'
    owner: false
    group: false
  when: not docker_compose_file.stat.exists

- name: Warn user that docker-compse file exists and migration was skipped
  debug:
    msg: "[WARNING]: Containers data folder seems to be in place, migration was aborted\nRemove {{ containers_dir }} and run again to proceed!!!"
  when: docker_compose_file.stat.exists
