---
- name: Install Wireguard and dependencies
  become: true
  package:
    name: 
      - wireguard
      - resolvconf
    state: present
    update_cache: yes

- name: Enable wireguard service
  become: true
  service:
    name: wg-quick@wg0
    enabled: yes